// autogenerated

use volatile;
use bit_field::BitField;

# [ doc = "USB on the go full speed" ]
# [ repr ( C ) ]
pub struct OtgFsPwrclk {
    # [ doc = "0x00 - OTG_FS power and clock gating control register (OTG_FS_PCGCCTL)" ]
    pub otg_fs_pcgcctl: volatile::ReadWrite<OtgFsPcgcctl>,
}

# [ derive ( Debug , Clone , Copy , PartialEq , Eq ) ]
# [ repr ( C ) ]
pub struct OtgFsPcgcctl {
    bits: u32,
}

impl OtgFsPcgcctl {
    # [ doc = "Bit 0 - Stop PHY clock" ]
    pub fn stppclk(&self) -> bool {
        self.bits.get_bit(0u8)
    }
    # [ doc = "Bit 1 - Gate HCLK" ]
    pub fn gatehclk(&self) -> bool {
        self.bits.get_bit(1u8)
    }
    # [ doc = "Bit 4 - PHY Suspended" ]
    pub fn physusp(&self) -> bool {
        self.bits.get_bit(4u8)
    }
}

impl Default for OtgFsPcgcctl {
    # [ doc = r" Reset value" ]
    fn default() -> Self {
        OtgFsPcgcctl { bits: 0u32 }
    }
}

impl OtgFsPcgcctl {
    # [ doc = "Bit 0 - Stop PHY clock" ]
    pub fn set_stppclk(&mut self, value: bool) {
        self.bits.set_bit(0u8, value);
    }
    # [ doc = "Bit 1 - Gate HCLK" ]
    pub fn set_gatehclk(&mut self, value: bool) {
        self.bits.set_bit(1u8, value);
    }
    # [ doc = "Bit 4 - PHY Suspended" ]
    pub fn set_physusp(&mut self, value: bool) {
        self.bits.set_bit(4u8, value);
    }
}
